---
kind: ImagePolicy
apiVersion: image.toolkit.fluxcd.io/v1beta2
metadata:
  name: infra-mgr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: infra-mgr
  policy:
    semver:
      range: x.x.x-0
