apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: couchdb
  namespace: infra-couchdb
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
          type: servicebinding.io/couchdb
    name: couchdb
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: infra-couchdb
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: couchdb
  namespace: infra-couchdb
spec:
  interval: 1h0s
  url: https://apache.github.io/couchdb-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: couchdb
  namespace: infra-couchdb
spec:
  releaseName: infra
  chart:
    spec:
      chart: couchdb
      version: 4.5.3
      sourceRef:
        kind: HelmRepository
        name: couchdb
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
    crds: CreateReplace
  interval: 10m0s
  timeout: 5m
  values:
    clusterSize: 1
    createAdminSecret: true
    couchdbConfig:
      couchdb:
        uuid: b18cdcd752c0416b8bd255760a94c8bc
    autoSetup:
      enabled: true
      image:
        repository: curlimages/curl
        tag: latest
        pullPolicy: Always
      defaultDatabases:
        - _global_changes